Chores
unepwcmc/web-components pull request #96
Opened 2022-10-24 16:33 UTC by Joseph-Burke

## Chores (no ticket)

This PR contains 3 chore commits concerned with linting the codebase, updating the README, setting dependency versions.

These 3 commits are present in other branches such as `feat/sorting`, so the idea here is that we merge this into `develop` and reduce the diff between the branches, making subsequent merges plainer, quicker and safer.

2022-10-24 17:06 UTC, WillKocur requested changes
Looks good - checked loading the site and both the list and api endpoints 👍 

One small comment about a strange whitespace thing and another about including instance methods, but happy for you to merge once addressed :)

2022-10-27 08:51 UTC, Joseph-Burke commented on wcmc_components/lib/wcmc_components/loadable.rb
>        base.send :include, InstanceMethods
Not 100% sure _but_:

- The `base.send` line is from Ben's original code, 3 years old now.
- The `InstanceMethods` module (line 12) is empty.

Between those two facts, I think it's probably safe to remove this from Loadable as it has been from Filterable.

2022-10-27 08:52 UTC, Joseph-Burke commented on wcmc_components/lib/wcmc_components/loadable.rb
>        base.send :include, InstanceMethods
I'm also going to remove the empty InstanceMethods module. I think this is probably from boilerplate or something like that, not having any effect on our code right now

2022-10-27 08:54 UTC, Joseph-Burke commented on wcmc_components/lib/wcmc_components/loadable.rb
>        base.send :include, InstanceMethods
Addressed in ac6419d6d2aab90e84350aa2002cf27ba98502c9

2022-10-27 08:59 UTC, Joseph-Burke commented on lib/capistrano/tasks/config.rake
> +      #{'  '}
Hahaha that is weird.

Honestly I think it has no real effect on the code to have these interpolated strings here. I'm going to remove these so it looks more like how it was previously.

<img width="639" alt="Screenshot 2022-10-27 at 10 58 32" src="https://user-images.githubusercontent.com/56026099/198240521-85c6bfad-8623-4a03-a613-6383219d5b82.png">

2022-10-27 09:01 UTC, Joseph-Burke commented on lib/capistrano/tasks/config.rake
> +      #{'  '}
Fixed in f5212904a3ce19cdadb6d71965fa4e126faf918b

2022-10-27 09:07 UTC, Joseph-Burke commented
Merging these in without a second review

2022-10-27 09:07 UTC, merged